### ISSUE TITLE
Error when generate assembly fingerprint

### ISSUE THREAD

**Issue by alienzj** [pbelmann/CamiClient#6]
```
$ java -jar camiClient.jar -af contigs.polished.fasta

Validation finished
Starting to compute fingerprint
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
at cami.hash.MD5Sum.getFingerprint(MD5Sum.java:27)
at cami.hash.MD5Sum.getFingerprint(MD5Sum.java:12)
at cami.CLI.computeFingerprint(CLI.java:390)
at cami.CLI.runValidateAssembly(CLI.java:183)
at cami.CLI.processCommandLine(CLI.java:138)
at cami.CLI.main(CLI.java:401)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 6 more
```

Help please~

**Comment by alienzj** [comment]
```
$ java --version

openjdk 11.0.1 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)
```

**Comment by alienzj** [comment]
```
$ java -jar camiClient.jar --version

Version:1.9.0
```

**Comment by alienzj** [comment]
But on my local computer, it can run:

```
$ java -jar camiClient.jar -af contigs.polished.fasta
Validation finished
Starting to compute fingerprint
Use this fingerprint in the cami website: 9526DA6313430E9C764935372D8F3BA6190

$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

$ java -jar camiClient.jar --version
Version:1.9.0
```
